In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/Housing.csv")

In [4]:
df.shape

(545, 13)

In [6]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [8]:
pd.get_dummies(df["furnishingstatus"]).head()

   furnished  semi-furnished  unfurnished
0       True           False        False
1       True           False        False
2      False            True        False
3       True           False        False
4       True           False        False

In [9]:
pd.get_dummies(df["furnishingstatus"], drop_first=True).head()

   semi-furnished  unfurnished
0           False        False
1           False        False
2            True        False
3           False        False
4           False        False

In [13]:
predictors = ["area", "furnishingstatus", "basement", "bedrooms"]
X = pd.get_dummies(df[predictors], drop_first=True)
X.head()

,area,bedrooms,furnishingstatus_semi-furnished,furnishingstatus_unfurnished,basement_yes
0,7420,4,False,False,False
1,8960,4,False,False,False
2,9960,3,True,False,True
3,7500,4,False,False,True
4,7420,4,False,False,True