In [40]:
import pandas as pd

import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

import numpy as np


from dmba import stepwise_selection
from dmba import AIC_score

In [2]:
df = pd.read_csv("data/kc_house_data.csv")

In [4]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,NaN,0.0,...,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,...,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0.0,0.0,...,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,...,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,...,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503

In [ ]:
# In multiple linear regression, each new predictor has a coefficient and they're all added
# together, SIMPLY
# Each predictor contributes independently and proportionally to the target, as though others were not there
# Meaning you could take each predictor and the target variable and create a simple linear model with it

In [5]:
df.shape

(21597, 21)

In [6]:
df.isin(['?']).sum()

id                 0
date               0
price              0
bedrooms           0
bathrooms          0
sqft_living        0
sqft_lot           0
floors             0
waterfront         0
view               0
condition          0
grade              0
sqft_above         0
sqft_basement    454
yr_built           0
yr_renovated       0
zipcode            0
lat                0
long               0
sqft_living15      0
sqft_lot15         0
dtype: int64

In [7]:
df.replace('?', np.nan, inplace=True)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,NaN,0.0,...,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,...,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0.0,0.0,...,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,...,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,...,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,263000018,5/21/2014,360000.0,3,2.50,1530,1131,3.0,0.0,0.0,...,8,1530,0.0,2009,0.0,98103,47.6993,-122.346,1530,1509
21593,6600060120,2/23/2015,400000.0,4,2.50,2310,5813,2.0,0.0,0.0,...,8,2310,0.0,2014,0.0,98146,47.5107,-122.362,1830,7200
21594,1523300141,6/23/2014,402101.0,2,0.75,1020,1350,2.0,0.0,0.0,...,7,1020,0.0,2009,0.0,98144,47.5944,-122.299,1020,2007
21595,291310100,1/16/2015,400000.0,3,2.50,1600,2388,2.0,NaN,0.0,...,8,1600,0.0,2004,0.0,98027,47.5345,-122.069,1410,1287
21596,1523300157,10/15/2014,325000.0,2,0.75,1020,1076,2.0,0.0,0.0,...,7,1020,0.0,2008,0.0,98144,47.5941,-122.299,1020,1357

In [8]:
df.isin(['?']).sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [9]:
df.isna().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2376
view               63
condition           0
grade               0
sqft_above          0
sqft_basement     454
yr_built            0
yr_renovated     3842
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isna().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [ ]:
# MODEL SELECTION 

# In multiple linear regression, when choosing which model is the best, using RMSE or R2 is not usually the best
# Adding more variables naturally increases R2 and reduces RMSE for the training data

# Use AIC, AICc, BIC or Mallows Cp, R2 adjusted
# AIC penalizes adding terms; k variables penalized by 2k
# So our goal is to minimize AIC or maximize R2 adjusted

# subset regression: trying every possible model
# stepwise
  # - forward selection
  # - backward elimination
  # - adding and removing while comparing AIC and adjusted R2

In [45]:
# We start with a few predictors
predictors = [
    "sqft_living", 
    "sqft_lot", 
    "bedrooms", 
    "bathrooms", 
    "grade"
]
outcome = "price"

x, y = df[predictors], df[outcome]

In [46]:
sk_model = LinearRegression()
sk_model.fit(x, y)

LinearRegression()

In [49]:
fitted_base = sk_model.predict(x)

r2_base = r2_score(y, fitted_base)
rmse_base = np.sqrt(mean_squared_error(y, fitted_base))

print(f"R2: {r2_base:.2f}")
print(f"RMSE: {rmse_base:.2f}")

R2: 0.55
RMSE: 251023.54

In [43]:
print(f'Intercept: {sk_model.intercept_:.3f}')
print('Coefficients:')

for name, coef in zip(predictors, sk_model.coef_):
    print(f' {name}: {coef}')

Intercept: -455208.312
Coefficients:
 sqft_living: 242.63732952411277
 sqft_lot: -0.33769660366526555
 bedrooms: -43140.322116111485
 bathrooms: -28296.262381399603
 grade: 91547.13144816356

In [48]:
# Let's use statsmodels to check things out
sm_model = sm.OLS(y, x.assign(const=1))
results = sm_model.fit()

results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.547
Model:                            OLS   Adj. R-squared:                  0.547
Method:                 Least Squares   F-statistic:                     3726.
Date:                Thu, 02 Apr 2026   Prob (F-statistic):               0.00
Time:                        09:10:07   Log-Likelihood:            -2.1373e+05
No. Observations:               15429   AIC:                         4.275e+05
Df Residuals:                   15423   BIC:                         4.275e+05
Df Model:                           5
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
sqft_living   242.6373      4.337     55.949      0.000     234.137     251.138
sqft_lot       -0.3377      0.049     -6.881      0.000      -0.434      -0.242
bedrooms    -4.314e+04   2730.196    -15.801      0.000   -4.85e+04   -3.78e+04
bathrooms    -2.83e+04   4177.735     -6.773      0.000   -3.65e+04   -2.01e+04
grade        9.155e+04   2789.378     32.820      0.000    8.61e+04     9.7e+04
const       -4.552e+05   1.79e+04    -25.372      0.000    -4.9e+05    -4.2e+05
==============================================================================
Omnibus:                    12073.165   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           719108.573
Skew:                           3.278   Prob(JB):                         0.00
Kurtosis:                      35.796   Cond. No.                     4.02e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.02e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
# Adding more predictor variables
predictors_2 = predictors + ["sqft_basement", "waterfront", "yr_built", "yr_renovated"]
x2 = df[predictors_2]

In [20]:
x2["sqft_basement"] = pd.to_numeric(x2["sqft_basement"], errors="coerce")

In [21]:
sm_model = sm.OLS(y, x2.assign(const=1))
results = sm_model.fit()

results.summary()

# Adjusted R² is always ≤ R²
# The new variables (sqft_basement, waterfront, yr_built, yr_renovated) are actually adding real predictive value, not just noise.
# If:

# your dataset is large
# and your added variables are useful

# 👉 then the penalty term becomes tiny

# So:

# Adjusted R² ≈ R²
# Difference becomes almost invisible

# A significant difference between R2 and Adjusted R2 is a sign of overfitting

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.648
Model:                            OLS   Adj. R-squared:                  0.648
Method:                 Least Squares   F-statistic:                     3151.
Date:                Thu, 02 Apr 2026   Prob (F-statistic):               0.00
Time:                        08:20:59   Log-Likelihood:            -2.1179e+05
No. Observations:               15429   AIC:                         4.236e+05
Df Residuals:                   15419   BIC:                         4.237e+05
Df Model:                           9
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
sqft_living     184.6316      4.219     43.764      0.000     176.362     192.901
sqft_lot         -0.2610      0.043     -6.014      0.000      -0.346      -0.176
bedrooms      -4.303e+04   2422.353    -17.763      0.000   -4.78e+04   -3.83e+04
bathrooms       5.66e+04   4064.151     13.926      0.000    4.86e+04    6.46e+04
grade          1.276e+05   2603.424     49.011      0.000    1.22e+05    1.33e+05
sqft_basement    -0.5733      4.837     -0.119      0.906     -10.055       8.908
waterfront     7.583e+05   2.09e+04     36.205      0.000    7.17e+05    7.99e+05
yr_built      -3901.2591     79.780    -48.900      0.000   -4057.637   -3744.882
yr_renovated      7.9875      4.724      1.691      0.091      -1.272      17.247
const          6.892e+06   1.52e+05     45.204      0.000    6.59e+06    7.19e+06
==============================================================================
Omnibus:                    11569.374   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           816230.660
Skew:                           3.000   Prob(JB):                         0.00
Kurtosis:                      38.123   Cond. No.                     3.82e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.82e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [23]:
print("r2: ", results.rsquared)
print("r2 adj: ", results.rsquared_adj)

# r2 adj is less than r2 as expected. Although not significantly, which is a good thing

# Also, AIC is significantly different between the two models: 427,500−423,600=3,900
# <2: no real difference, 4 to 10: some, >10 strong, >>10 very strong evidence
# You can only compare AIC values when:
#   - Models are fit on the same dataset
#   - Same target variable

r2:  0.647776885835211
r2 adj:  0.6475712948093673

In [97]:
results.rsquared - results.rsquared_adj

np.float64(0.00020559102584372102)

In [98]:
# removing sqft_basement and yr_renovated since their p values showed they're insignificant in the second model
predictors_3 = predictors + ["waterfront", "yr_built"]
x3 = df[predictors_3]

sm_model_3 = sm.OLS(y, x3.assign(const=1))
results = sm_model_3.fit()

results.summary()

# turns out they were truly insignificant since r-squared adj and AIC remained thesame

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.648
Model:                            OLS   Adj. R-squared:                  0.648
Method:                 Least Squares   F-statistic:                     4050.
Date:                Sun, 22 Mar 2026   Prob (F-statistic):               0.00
Time:                        14:48:16   Log-Likelihood:            -2.1179e+05
No. Observations:               15429   AIC:                         4.236e+05
Df Residuals:                   15421   BIC:                         4.237e+05
Df Model:                           7
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
sqft_living   184.3124      3.928     46.921      0.000     176.613     192.012
sqft_lot       -0.2606      0.043     -6.018      0.000      -0.346      -0.176
bedrooms    -4.318e+04   2420.599    -17.839      0.000   -4.79e+04   -3.84e+04
bathrooms    5.754e+04   4011.032     14.345      0.000    4.97e+04    6.54e+04
grade        1.278e+05   2546.653     50.178      0.000    1.23e+05    1.33e+05
waterfront   7.604e+05   2.09e+04     36.400      0.000    7.19e+05    8.01e+05
yr_built    -3935.7281     74.167    -53.066      0.000   -4081.105   -3790.351
const        6.958e+06   1.41e+05     49.398      0.000    6.68e+06    7.23e+06
==============================================================================
Omnibus:                    11581.532   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           819410.828
Skew:                           3.004   Prob(JB):                         0.00
Kurtosis:                      38.192   Cond. No.                     3.53e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.53e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
# Stepwise Regression
# stepwise_selection, forward_selection, and backward_elimination

X = x2
def train_model(variables):
    if len(variables) == 0:
        return None
    model = LinearRegression()
    model.fit(X[variables], y)
    return model


def score_model(model, variables):
    if len(variables) == 0:
        return AIC_score(y, [y.mean()] * len(y), model, df=1)
    return AIC_score(y, model.predict(X[variables]), model)

In [34]:
best_model, best_variables = stepwise_selection(
    X.columns, 
    train_model, 
    score_model, 
    verbose=True
)

print()
print(f'Intercept: {best_model.intercept_:.3f}')
print('Coefficients:')
for name, coef in zip(best_variables, best_model.coef_):
    print(f' {name}: {coef}')

Variables: sqft_living, sqft_lot, bedrooms, bathrooms, grade, sqft_basement, waterfront, yr_built, yr_renovated
Start: score=439678.00, constant
Step: score=429011.95, add sqft_living
Step: score=427767.69, add waterfront
Step: score=426467.89, add grade
Step: score=424054.12, add yr_built
Step: score=423841.47, add bedrooms
Step: score=423629.06, add bathrooms
Step: score=423594.88, add sqft_lot
Step: score=423594.00, add yr_renovated
Step: score=423594.00, unchanged None

Intercept: 6886704.926
Coefficients:
 sqft_living: 184.449443595943
 waterfront: 758221.2016671114
 grade: 127660.86704263036
 yr_built: -3898.9101986877445
 bedrooms: -43033.31458253572
 bathrooms: 56559.50920916256
 sqft_lot: -0.26066118699964136
 yr_renovated: 8.00556131375697

In [37]:
x.columns

Index(['sqft_living', 'sqft_lot', 'bedrooms', 'bathrooms', 'grade'], dtype='str')

In [38]:
x2.columns

Index(['sqft_living', 'sqft_lot', 'bedrooms', 'bathrooms', 'grade',
       'sqft_basement', 'waterfront', 'yr_built', 'yr_renovated'],
      dtype='str')

In [42]:
fitted = best_model.predict(X[best_variables])

r2 = r2_score(y, fitted)
rmse = np.sqrt(mean_squared_error(y, fitted))

print(f"R2: {r2:.2f}")
print(f"RMSE: {rmse:.2f}")

R2: 0.65
RMSE: 221375.44